# Generated by Django 4.1.6 on 2023-04-17 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdrp.fields


class Migration(migrations.Migration):

    replaces = [('gdrp', '0001_initial'), ('gdrp', '0002_product_price_points'), ('gdrp', '0003_alter_user_sponsorid'), ('gdrp', '0004_profile_user_old_alter_order_userid_delete_user'), ('gdrp', '0005_remove_profile_id_profile_phone_and_more'), ('gdrp', '0006_delete_user_old'), ('gdrp', '0007_alter_product_catalog_productids'), ('gdrp', '0008_promotion_product_tags'), ('gdrp', '0009_auto_20230314_1444'), ('gdrp', '0010_product_inventory_alter_product_image'), ('gdrp', '0011_profile_known_ips'), ('gdrp', '0012_product_inventory_alter_product_categories_and_more'), ('gdrp', '0013_product_inventory_alter_product_categories_and_more'), ('gdrp', '0014_product_inventory_alter_product_image_and_more'), ('gdrp', '0015_product_inventory_alter_product_catalog_productids'), ('gdrp', '0016_product_inventory_alter_product_image_and_more'), ('gdrp', '0017_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0018_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0019_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0020_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0021_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0022_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0023_rename_oderid_order_details_orderid_and_more'), ('gdrp', '0024_product_inventory_profile_ebay_username_and_more'), ('gdrp', '0025_product_inventory_alter_product_catalog_productids'), ('gdrp', '0026_product_inventory_profile_ebay_username_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Product', max_length=255)),
                ('description', models.CharField(default='[Product Description]', max_length=5500)),
                ('price_dollars', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='')),
                ('price_points', models.IntegerField(default=0)),
                ('tags', gdrp.fields.SeparatedTextField(blank=True)),
                ('categories', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sponsor', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product_catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductIDs', models.ManyToManyField(blank=True, to='gdrp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('point_total', models.IntegerField(default=0)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.FloatField(default=0.01)),
                ('product_catalog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gdrp.product_catalog')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdrp.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('OrderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gdrp.order')),
                ('quantity', models.IntegerField(default=0)),
                ('products', models.ManyToManyField(to='gdrp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='#PROMOTION_NAME', max_length=255)),
                ('description', models.CharField(default='#PROMO_DESCRIPTION', max_length=255)),
                ('multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion_l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ManyToManyField(blank=True, to='gdrp.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('points', models.IntegerField(blank=True, default=0)),
                ('SponsorID', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='gdrp.sponsor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.IntegerField(null=True)),
                ('promotions', models.ManyToManyField(to='gdrp.promotion')),
                ('known_ips', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('approved', models.BooleanField(default=False)),
                ('sponsor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gdrp.sponsor')),
            ],
        ),
    ]
