# Generated by Django 4.1.6 on 2023-02-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0002_product_price_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='SponsorID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='gdrp.sponsor'),
        ),
    ]
