# Generated by Django 4.1.6 on 2023-02-16 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrp', '0003_alter_user_sponsorid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('SponsorID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gdrp.sponsor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_old',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='a@b.c', max_length=254)),
                ('user_type', models.CharField(default='Driver', max_length=50)),
                ('name', models.CharField(default='first last', max_length=255)),
                ('points', models.IntegerField(default=0)),
                ('SponsorID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gdrp.sponsor')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
