# Generated by Django 4.1.6 on 2023-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0006_delete_user_old'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_catalog',
            name='ProductIDs',
            field=models.ManyToManyField(blank=True, to='gdrp.product'),
        ),
    ]
