# Generated by Django 3.2.16 on 2023-03-14 18:44

from django.db import migrations, models
import gdrp.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0008_promotion_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=gdrp.fields.SeparatedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='promotions',
            field=models.ManyToManyField(to='gdrp.Promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(default='#PROMOTION_NAME', max_length=255),
        ),
        migrations.CreateModel(
            name='Promotion_l',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ManyToManyField(blank=True, to='gdrp.Promotion')),
            ],
        ),
    ]
