# Generated by Django 4.1.6 on 2023-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0009_auto_20230314_1444'),
    ]

    operations = [
    ]
