# Generated by Django 4.1.6 on 2023-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0010_product_inventory_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='known_ips',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
