# Generated by Django 4.1.6 on 2023-04-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0011_profile_known_ips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
