# Generated by Django 4.1.6 on 2023-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0012_product_inventory_alter_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
