# Generated by Django 4.1.6 on 2023-04-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0014_product_inventory_alter_product_image_and_more'),
    ]

    operations = [
    ]
