# Generated by Django 4.1.6 on 2023-04-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0016_product_inventory_alter_product_image_and_more'),
    ]

    operations = [
    ]
