# Generated by Django 4.1.6 on 2023-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0020_product_inventory_profile_ebay_username_and_more'),
    ]

    operations = [
    ]
