# Generated by Django 4.1.6 on 2023-04-08 16:21

from django.db import migrations, models
from gdrp.models import User


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0021_product_inventory_profile_ebay_username_and_more'),
    ]

    operations = [
    ]
