# Generated by Django 4.1.6 on 2023-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0022_product_inventory_profile_ebay_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_details',
            old_name='OderID',
            new_name='OrderID',
        ),
    ]
