# Generated by Django 4.1.6 on 2023-04-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrp', '0023_rename_oderid_order_details_orderid_and_more'),
    ]

    operations = [
    ]
